language: cpp

compiler:
- gcc
- clang

before_install:
- sudo add-apt-repository -y ppa:afrank/boost
- sudo apt-get update -qq

install:
- sudo apt-get install libboost-system-dev libboost-asio-dev

before_script:
- cd .. && mkdir build && cd build
- cmake ../pgaro

script:
- make all
